export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';

export const FETCH_CATEGORY_ADMIN = 'FETCH_CATEGORY_ADMIN';
export const FETCH_CATEGORY_SUCCESS_ADMIN = 'FETCH_CATEGORY_SUCCESS_ADMIN';
export const FETCH_CATEGORY_FAILED_ADMIN = 'FETCH_CATEGORY_FAILED_ADMIN';

export const FETCH_CATEGORY_ADMIN_FULL = 'FETCH_CATEGORY_ADMIN_FULL';
export const FETCH_CATEGORY_SUCCESS_ADMIN_FULL = 'FETCH_CATEGORY_SUCCESS_ADMIN_FULL';
export const FETCH_CATEGORY_FAILED_ADMIN_FULL = 'FETCH_CATEGORY_FAILED_ADMIN_FULL';

export const FETCH_SUBCATEGORY = 'FETCH_SUBCATEGORY';
export const FETCH_SUBCATEGORY_SUCCESS = 'FETCH_SUBCATEGORY_SUCCESS';
export const FETCH_SUBCATEGORY_FAILED = 'FETCH_SUBCATEGORY_FAILED';



export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const FILTER_CATEGORY_SUCCESS = 'FILTER_CATEGORY_SUCCESS';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';

export const SET_CATEGORY_EDITING = 'SET_CATEGORY_EDITING';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';
