export const FETCH_ORDERSTATUS = 'FETCH_ORDERSTATUS';
export const FETCH_ORDERSTATUS_SUCCESS = 'FETCH_ORDERSTATUS_SUCCESS';
export const FETCH_ORDERSTATUS_FAILED = 'FETCH_ORDERSTATUS_FAILED';

export const DELETE_ORDERSTATUS = 'DELETE_ORDERSTATUS';
export const DELETE_ORDERSTATUS_SUCCESS = 'DELETE_ORDERSTATUS_SUCCESS';
export const DELETE_ORDERSTATUS_FAILED = 'DELETE_ORDERSTATUS_FAILED';

export const ADD_ORDERSTATUS = 'ADD_ORDERSTATUS';
export const ADD_ORDERSTATUS_SUCCESS = 'ADD_ORDERSTATUS_SUCCESS';
export const ADD_ORDERSTATUS_FAILED = 'ADD_ORDERSTATUS_FAILED';

export const SET_ORDERSTATUS_EDITING = 'SET_ORDERSTATUS_EDITING';

export const UPDATE_ORDERSTATUS = 'UPDATE_ORDERSTATUS';
export const UPDATE_ORDERSTATUS_SUCCESS = 'UPDATE_ORDERSTATUS_SUCCESS';
export const UPDATE_ORDERSTATUS_FAILED = 'UPDATE_ORDERSTATUS_FAILED';