export const FETCH_ORDER = 'FETCH_ORDER';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED';

export const DELETE_LIST_CART = 'DELETE_LIST_CART';

export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILED = 'DELETE_ORDER_FAILED';

export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAILED = 'ADD_ORDER_FAILED';

export const SET_ORDER_EDITING = 'SET_ORDER_EDITING';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAILED = 'UPDATE_ORDER_FAILED';

export const FETCH_USER_ORDER = 'FETCH_USER_ORDER';
export const FETCH_USER_ORDER_SUCCESS = 'FETCH_USER_ORDER_SUCCESS';

export const FETCH_ORDER_BYID = 'FETCH_ORDER_BYID';
export const FETCH_ORDER_SUCCESS_BYID = 'FETCH_ORDER_SUCCESS_BYID';
export const FETCH_ORDER_FAILED_BYID = 'FETCH_ORDER_FAILED_BYID';

