export const FETCH_PRODUCTSTATUS = 'FETCH_PRODUCTSTATUS';
export const FETCH_PRODUCTSTATUS_SUCCESS = 'FETCH_PRODUCTSTATUS_SUCCESS';
export const FETCH_PRODUCTSTATUS_FAILED = 'FETCH_PRODUCTSTATUS_FAILED';

export const DELETE_PRODUCTSTATUS = 'DELETE_PRODUCTSTATUS';
export const DELETE_PRODUCTSTATUS_SUCCESS = 'DELETE_PRODUCTSTATUS_SUCCESS';
export const DELETE_PRODUCTSTATUS_FAILED = 'DELETE_PRODUCTSTATUS_FAILED';

export const ADD_PRODUCTSTATUS = 'ADD_PRODUCTSTATUS';
export const ADD_PRODUCTSTATUS_SUCCESS = 'ADD_PRODUCTSTATUS_SUCCESS';
export const ADD_PRODUCTSTATUS_FAILED = 'ADD_PRODUCTSTATUS_FAILED';

export const SET_PRODUCTSTATUS_EDITING = 'SET_PRODUCTSTATUS_EDITING';

export const UPDATE_PRODUCTSTATUS = 'UPDATE_PRODUCTSTATUS';
export const UPDATE_PRODUCTSTATUS_SUCCESS = 'UPDATE_PRODUCTSTATUS_SUCCESS';
export const UPDATE_PRODUCTSTATUS_FAILED = 'UPDATE_PRODUCTSTATUS_FAILED';