export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';
export const FETCH_DETAIL_PRODUCT = 'FETCH_DETAIL_PRODUCT';
export const FETCH_DETAIL_PRODUCT_SUCCESS = 'FETCH_DETAIL_PRODUCT_SUCCESS';
export const FETCH_DETAIL_PRODUCT_FAILED = 'FETCH_DETAIL_PRODUCT_FAILED';

export const FETCH_PRODUCT_CATEGORY = 'FETCH_PRODUCT_CATEGORY';
export const FETCH_PRODUCT_CATEGORY_SUCCESS = 'FETCH_PRODUCT_CATEGORY_SUCCESS';

export const FETCH_PRODUCT_SEARCH = 'FETCH_PRODUCT_SEARCH';
export const FETCH_PRODUCT_SEARCH_SUCCESS = 'FETCH_PRODUCT_SEARCH_SUCCESS';

export const FETCH_PRODUCT_ADMIN = 'FETCH_PRODUCT_ADMIN';
export const FETCH_PRODUCT_SUCCESS_ADMIN = 'FETCH_PRODUCT_SUCCESS_ADMIN';
export const FETCH_PRODUCT_FAILED_ADMIN = 'FETCH_PRODUCT_FAILED_ADMIN';


export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';

export const SET_PRODUCT_EDITING = 'SET_PRODUCT_EDITING';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';