export const FETCH_PRODUCER = 'FETCH_PRODUCER';
export const FETCH_PRODUCER_SUCCESS = 'FETCH_PRODUCER_SUCCESS';
export const FETCH_PRODUCER_FAILED = 'FETCH_PRODUCER_FAILED';

export const DELETE_PRODUCER = 'DELETE_PRODUCER';
export const DELETE_PRODUCER_SUCCESS = 'DELETE_PRODUCER_SUCCESS';
export const DELETE_PRODUCER_FAILED = 'DELETE_PRODUCER_FAILED';

export const ADD_PRODUCER = 'ADD_PRODUCER';
export const ADD_PRODUCER_SUCCESS = 'ADD_PRODUCER_SUCCESS';
export const ADD_PRODUCER_FAILED = 'ADD_PRODUCER_FAILED';

export const SET_PRODUCER_EDITING = 'SET_PRODUCER_EDITING';

export const UPDATE_PRODUCER = 'UPDATE_PRODUCER';
export const UPDATE_PRODUCER_SUCCESS = 'UPDATE_PRODUCER_SUCCESS';
export const UPDATE_PRODUCER_FAILED = 'UPDATE_PRODUCER_FAILED';