
export const FETCH_REVIEW_PRODUCT = 'FETCH_REVIEW_PRODUCT';
export const FETCH_REVIEW_PRODUCT_SUCCESS = 'FETCH_REVIEW_PRODUCT_SUCCESS';
export const ADD_REVIEW_PRODUCT_SUCCESS = 'ADD_REVIEW_PRODUCT_SUCCESS';

