export const FETCH_STATUS = 'FETCH_STATUS';
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS';
export const FETCH_STATUS_FAILED = 'FETCH_STATUS_FAILED';

export const DELETE_STATUS = 'DELETE_STATUS';
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS';
export const DELETE_STATUS_FAILED = 'DELETE_STATUS_FAILED';

export const ADD_STATUS = 'ADD_STATUS';
export const ADD_STATUS_SUCCESS = 'ADD_STATUS_SUCCESS';
export const ADD_STATUS_FAILED = 'ADD_STATUS_FAILED';

export const SET_STATUS_EDITING = 'SET_STATUS_EDITING';

export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAILED = 'UPDATE_STATUS_FAILED';